mqtt_settings:
  port: 1883
  server: dshared.de


graphs:
  Smoker:
    'Oven Temp':
      topic: hallomanuel
      json_template: '{{ oven_temp }}'
    'Meat Temp':
      topic: hallomanuel
      json_template: '{{ meat_temp }}'


web_settings:
  host: 0.0.0.0
  password: admin123
  port: 3000
  username: admin
